version: '3.1'

services:

  phpmyadmin:
    image: bitnami/phpmyadmin
    container_name: phpmyadmin
    ports:
      - 18181:8080
      - 18443:8143
    restart: always
    depends_on:
      - mariadb
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=123456
      - PHPMYADMIN_ALLOW_ARBITRARY_SERVER=yes

  mongoui:
    image: mongo-express
    container_name: mongoui
    restart: always
    ports:
      - 18182:8081
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=123456
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_URL="mongodb://root:123456@mongodb:27017/"

  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=root

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456

