version: "3"

services:

  db:
    image: mariadb
    restart: unless-stopped
    container_name: piwigo_db
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_PASSWORD=piwigo
      - MYSQL_DATABASE=piwigo
      - MYSQL_USER=piwigo

  piwigo:
    image: lscr.io/linuxserver/piwigo
    container_name: piwigo
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - ./config:/config
      - ./gallery:/gallery
      - /album:/gallery/album
    ports:
      - 9039:80
      - 9040:443
    restart: unless-stopped
