version: "3"

services:

  db:
    image: mariadb
    restart: always
    container_name: nextcloud_db
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --skip-innodb-read-only-compressed
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  rds:
    image: redis
    restart: always
    container_name: nextcloud_rds

  oo:
    image: onlyoffice/documentserver
    container_name: onlyoffice
    restart: always
    volumes:
      - ./onlyoffice/logs:/var/log/onlyoffice
      - ./onlyoffice/data:/var/www/onlyoffice/data
    ports:
      - 80:80
      - 443:443

  nextcloud:
    image: lscr.io/linuxserver/nextcloud
    container_name: nextcloud
    links:
      - db
      - rds
      - oo
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/ShangHai
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
    volumes:
      - ./config:/config
      - /nchome:/data
      - /album:/album
      - /data:/nasdata
    ports:
      - 36123:443
    restart: unless-stopped
