version: "3"

services:

    siyuan:
      image: b3log/siyuan
      container_name: siyuan
      restart: unless-stopped
      ports:
        - 26806:6806
      volumes:
        - /appdata/siyuan:/docker/siyuan
      command:
        [--workspace=/docker/siyuan,--accessAuthCode=job647tuck411]
