version: '3'

services:

  webdav:
    image: ugeek/webdav:amd64
    container_name: all
    restart: always
    ports:
      - "26883:80"
    environment:
      - USERNAME=webdav
      - PASSWORD=webdav
      - UID=1000
      - GID=1000
      - TZ=Asia/Shanghai
    volumes:
      - ./media_all:/media
      - /nchome/public:/media/public
      - /album:/media/album
      - /data:/media/main

  media:
    image: ugeek/webdav:amd64
    container_name: public
    restart: always
    ports:
      - "26666:80"
    environment:
      - USERNAME=sean
      - PASSWORD=lovemymusic
      - UID=1000
      - GID=1000
      - TZ=Asia/Shanghai
    volumes:
      - ./media_public:/media
      - /data/public/music:/media/music
      - /album/seed/fsync:/media/fsync
      - /nchome/public:/media/public
