version: "3"

services:

  code-server:
    image: basedev
    container_name: devenv
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      # hash密码命令：printf "********"|sha256sum|cut -d' ' -f1
      - HASHED_PASSWORD=db953bb7b9caceb9d79a7aaf2487a27b961dbfec30183c39199f92528ae557bf #web密码
      - SUDO_PASSWORD=123456  #sudo操作密码
      #- SUDO_PASSWORD_HASH=db953bb7b9caceb9d79a7aaf2487a27b961dbfec30183c39199f92528ae557bf #sudo操作密码
      #- PROXY_DOMAIN=code-server.my.domain #optional
      #- DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      - ./root/custom-cont-init.d:/custom-cont-init.d
      - ./data:/config
      - ~/.ssh:/config/.ssh
      - ../:/config/workspace/services
    ports:
      - 32113:8443
    restart: unless-stopped
