version: "3"

services:

  jellyfin:
    image: linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - JELLYFIN_PublishedServerUrl=192.168.0.203
    volumes:
      - ./config:/config
      - /home/xinl/services/cert:/cert
      - /data:/data
      - /download:/download
    ports:
      - 38096:8096
      - 38920:8920 #https
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: always
