version: '3'

services:

  app:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    ports:
      - 9000:8000
      - 9002:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
