version: '3'

services:
  mysql:
    image: mysql:5.7
    restart: always
    container_name: mysql
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    networks:
      - pub

  phpmyadmin:
    image: phpmyadmin
    restart: always
    container_name: phpmyadmin
    ports:
      - 9006:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - pub

networks:
  pub:

