version: "3"

services:

  memos:
    container_name: memos
    image: elestio/memos
    restart: unless-stopped
    volumes:
      - ./data:/var/opt/memos
    ports:
      - 35230:5230
    logging:
      driver: json-file
      options:
        max-size: 1m
